# -*- coding: utf-8 -*-

# Macro Begin: /home/amcintosh/Documents/FreeCAD/tests/Macro/make-test-drawing.FCMacro +++++++++++++++++++++++++++++++++++++++++++++++++
import FreeCAD
import PartDesign
import PartDesignGui
import Sketcher
import math

App.newDocument("test-pipe")
App.ActiveDocument.addObject('PartDesign::Body','Body')
App.ActiveDocument.addObject('PartDesign::AdditiveBox','Box')
App.ActiveDocument.Body.addObject(App.ActiveDocument.Box)
App.ActiveDocument.Box.Length=304.800
App.ActiveDocument.Box.Width=304.800
App.ActiveDocument.Box.Height=304.800

App.ActiveDocument.Body.newObject('PartDesign::Plane','dp_diagonal')
App.ActiveDocument.dp_diagonal.Support = [(App.ActiveDocument.Box,'Vertex5'),(App.ActiveDocument.Box,'Vertex4'),(App.ActiveDocument.Box,'Vertex6')]
App.ActiveDocument.dp_diagonal.MapMode = 'ThreePointsPlane'
App.ActiveDocument.recompute()
App.ActiveDocument.dp_diagonal.MapReversed = False
App.ActiveDocument.dp_diagonal.Support = [(App.ActiveDocument.Box,'Vertex5'),(App.ActiveDocument.Box,'Vertex4'),(App.ActiveDocument.Box,'Vertex6')]
App.ActiveDocument.dp_diagonal.MapMode = 'ThreePointsPlane'
App.ActiveDocument.recompute()
#Gui.ActiveDocument.resetEdit()
App.ActiveDocument.Body.newObject('Sketcher::SketchObject','sk_diagonal')
App.ActiveDocument.sk_diagonal.Support = (App.ActiveDocument.dp_diagonal, [''])
App.ActiveDocument.sk_diagonal.MapMode = 'FlatFace'
App.ActiveDocument.recompute()
#Gui.activeDocument().activeView().viewIsometric()
App.ActiveDocument.sk_diagonal.addGeometry(Part.Point(App.Vector(143.511322,203.200000,0)))
App.ActiveDocument.recompute()
App.ActiveDocument.sk_diagonal.addGeometry(Part.Point(App.Vector(-287.379808,-101.600000,0)))
App.ActiveDocument.recompute()
App.ActiveDocument.sk_diagonal.addGeometry(Part.LineSegment(App.Vector(143.514826,203.200000,0),App.Vector(-287.376382,-101.600000,0)),False)
App.ActiveDocument.sk_diagonal.addConstraint(Sketcher.Constraint('Coincident',2,1,0,1)) 
App.ActiveDocument.sk_diagonal.addConstraint(Sketcher.Constraint('Coincident',2,2,1,1)) 
App.ActiveDocument.recompute()
#Gui.activeDocument().activeView().viewIsometric()
App.ActiveDocument.recompute()


App.ActiveDocument.Body.newObject('PartDesign::Plane','dp_starSupport')
App.ActiveDocument.dp_starSupport.Support = [(App.ActiveDocument.Box,'Vertex4'),(App.ActiveDocument.Box,'Vertex5')]
App.ActiveDocument.dp_starSupport.MapMode = 'InertialCS'

App.ActiveDocument.Body.newObject('Sketcher::SketchObject','Sketch001')
App.ActiveDocument.Sketch001.Support = (App.ActiveDocument.dp_starSupport, '')
App.ActiveDocument.Sketch001.MapMode = 'FlatFace'
App.ActiveDocument.recompute()

#Gui.activateWorkbench('PartDesignWorkbench')
App.ActiveDocument.Body.newObject("PartDesign::SubtractivePipe","SubtractivePipe")
App.ActiveDocument.SubtractivePipe.Profile = App.ActiveDocument.Sketch001
App.ActiveDocument.recompute()
#Gui.activeDocument().hide("Sketch001")
App.ActiveDocument.recompute()
Gui.activeDocument().activeView().viewIsometric()
# Macro End: /home/amcintosh/Documents/FreeCAD/tests/Macro/make-test-drawing.FCMacro +++++++++++++++++++++++++++++++++++++++++++++++++
