# -*- coding: utf-8 -*-

# Macro Begin: /home/amcintosh/Documents/FreeCAD/tests/Macro/star.FCMacro +++++++++++++++++++++++++++++++++++++++++++++++++
import FreeCAD

rot = App.Rotation(App.Vector(0, 0, 1),360/5)

vec = App.Vector(0, 25.4, 0)

vec2 = App.Vector(0, -1, 0)
vec2.Length = vec.Length*(math.cos(2*math.pi/5)/math.cos(2*math.pi/10))
vec2 = rot.multVec(vec2)
vec2 = rot.multVec(vec2)
vec2 = rot.multVec(vec2)
vec1 = vec2

App.ActiveDocument.Sketch.addGeometry(Part.LineSegment(vec,vec2),True)

vec = rot.multVec(vec)
App.ActiveDocument.Sketch.addGeometry(Part.LineSegment(vec,vec2),False)
vec2 = rot.multVec(vec2)
App.ActiveDocument.Sketch.addGeometry(Part.LineSegment(vec,vec2),False)
App.ActiveDocument.Sketch.addGeometry(Part.LineSegment(vec1,vec2),True)
vec1 = vec2

vec = rot.multVec(vec)
App.ActiveDocument.Sketch.addGeometry(Part.LineSegment(vec,vec2),False)
vec2 = rot.multVec(vec2)
App.ActiveDocument.Sketch.addGeometry(Part.LineSegment(vec,vec2),False)
App.ActiveDocument.Sketch.addGeometry(Part.LineSegment(vec1,vec2),True)
vec1 = vec2

vec = rot.multVec(vec)
App.ActiveDocument.Sketch.addGeometry(Part.LineSegment(vec,vec2),False)
vec2 = rot.multVec(vec2)
App.ActiveDocument.Sketch.addGeometry(Part.LineSegment(vec,vec2),False)
App.ActiveDocument.Sketch.addGeometry(Part.LineSegment(vec1,vec2),True)
vec1 = vec2

vec = rot.multVec(vec)
App.ActiveDocument.Sketch.addGeometry(Part.LineSegment(vec,vec2),False)
vec2 = rot.multVec(vec2)
App.ActiveDocument.Sketch.addGeometry(Part.LineSegment(vec,vec2),False)
App.ActiveDocument.Sketch.addGeometry(Part.LineSegment(vec1,vec2),True)
vec1 = vec2

vec = rot.multVec(vec)
App.ActiveDocument.Sketch.addGeometry(Part.LineSegment(vec,vec2),False)
vec2 = rot.multVec(vec2)
App.ActiveDocument.Sketch.addGeometry(Part.LineSegment(vec1,vec2),True)

App.ActiveDocument.Sketch.addConstraint(Sketcher.Constraint('Coincident',2,1,1,1)) 
App.ActiveDocument.Sketch.addConstraint(Sketcher.Constraint('Coincident',5,1,4,1)) 
App.ActiveDocument.Sketch.addConstraint(Sketcher.Constraint('Coincident',8,1,7,1)) 
App.ActiveDocument.Sketch.addConstraint(Sketcher.Constraint('Coincident',11,1,10,1)) 
App.ActiveDocument.Sketch.addConstraint(Sketcher.Constraint('Coincident',13,1,0,1)) 
# Macro End: /home/amcintosh/Documents/FreeCAD/tests/Macro/star.FCMacro +++++++++++++++++++++++++++++++++++++++++++++++++
